version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kams-shop-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kams_shop_db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kams_shop_network
    restart: always

  backend:
    build: ./backend
    container_name: kams-shop-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${POSTGRES_PORT}
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - kams_shop_network
    restart: always

  frontend:
    build: ./frontend
    container_name: kams-shop-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - kams_shop_network
    restart: always

networks:
  kams_shop_network:
    driver: bridge

volumes:
  kams_shop_db_data: